Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Models/ErrorViewModel.cs
using System;

namespace SEDC.PizzaApp.Refactored.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.PizzaApp.Refactored.Models;

namespace SEDC.PizzaApp.Refactored.Controllers
{
    public class HomeController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.PizzaApp.Services.Implementations;
using SEDC.PizzaApp.Services.Interfaces;
using SEDC.PizzaApp.ViewModels.Order;

namespace SEDC.PizzaApp.Refactored.Controllers
{
    public class OrderController : Controller
    {
        private IOrderService _orderService;
        private IUserService _userService;
        private IPizzaService _pizzaService;
        //called for each request
        //this is what the app does
        //new OrderController(new OrderService())
        public OrderController(IOrderService orderService, IUserService userService, IPizzaService pizzaService) // we are using Dependency Injection - needs to instantiate the service
        {
            //manual
            //_orderService = new OrderService();

            _orderService = orderService;
            _userService = userService;
            _pizzaService = pizzaService;
        }
        public IActionResult Index()
        {
            //call to business layer
            List<OrderDetailsViewModel> orderDetailsViewModels = _orderService.GetAllOrders();
            return View(orderDetailsViewModels);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return View("BadRequest");
            }

            try
            {
                OrderDetailsViewModel orderDetailsViewModel = _orderService.GetOrderById(id.Value);
                return View(orderDetailsViewModel);
            }
            catch(Exception ex)
            {
                return View("ExceptionView");
            }
        }

        public IActionResult CreateOrder()
        {
            OrderViewModel orderViewModel = new OrderViewModel();
            ViewBag.Users = _userService.GetUsersForDropDown();
            return View(orderViewModel);
        }

        [HttpPost]
        public IActionResult CreateOrderPost(OrderViewModel orderViewModel)
        {
            try
            {
                _orderService.CreateOrder(orderViewModel);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View("ExceptionView");
            }
            
        }

        public IActionResult AddPizza(int id)//order id
        {
            ViewBag.Pizzas = _pizzaService.GetPizzasForDropdown();
            PizzaOrderViewModel pizzaOrderViewModel = new PizzaOrderViewModel();
            //the order that gets the pizza
            pizzaOrderViewModel.OrderId = id;
            return View(pizzaOrderViewModel);
        }

        [HttpPost]
        public IActionResult AddPizzaPost(PizzaOrderViewModel pizzaOrderViewModel)
        {
            try
            {
                _orderService.AddPizzaToOrder(pizzaOrderViewModel);
                return RedirectToAction("Details", new {id = pizzaOrderViewModel.OrderId});
            }
            catch (Exception e)
            {
                return View("ExceptionView");
            }
        }
        //public IActionResult RemovePizza()
        //{

        //}
    }
}

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Controllers/PizzaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.PizzaApp.Services.Interfaces;
using SEDC.PizzaApp.ViewModels.Pizza;

namespace SEDC.PizzaApp.Refactored.Controllers
{
    public class PizzaController : Controller
    {
        private IPizzaService _pizzaService;
        public PizzaController(IPizzaService pizzaService)
        {
            _pizzaService = pizzaService;
        }
        public IActionResult Index()
        {
            List<PizzaDetailsViewModel> pizzaDetailsViewModels = _pizzaService.GetAllPizzas();
            return View(pizzaDetailsViewModels);
        }
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return View("BadRequest");
            }

            try
            {
                PizzaDetailsViewModel pizzaDetailsViewModel = _pizzaService.GetPizzaById(id.Value);
                return View(pizzaDetailsViewModel);
            }
            catch (Exception ex)
            {
                return View("ExceptionView");
            }
        }
        public IActionResult CreatePizza()
        {
            PizzaViewModel pizzaViewModel = new PizzaViewModel();
            ViewBag.Pizzas = _pizzaService.GetPizzasForDropdown();
            return View(pizzaViewModel);
        }

        [HttpPost]
        public IActionResult CreatePizzaPost(PizzaViewModel pizzaViewModel)
        {
            try
            {
                _pizzaService.CreatePizza(pizzaViewModel);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View("ExceptionView");
            }

        }
    }
}

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Order/AddPizza.cshtml
@model PizzaOrderViewModel
<h2>Add Pizza</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPizzaPost" method="post">
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="PizzaId" class="control-label"></label>
                <select class="form-control" asp-for="PizzaSize" asp-items="@(new SelectList(ViewBag.Pizzas,"Id","Name"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="PizzaSize" class="control-label"></label>
                <select class="form-control" asp-for="PizzaId" asp-items="Html.GetEnumSelectList<PizzaSize>()"></select>
               </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
            </div>
            <input type="submit" class="btn btn-default"/>
        </form>
    </div>
</div>

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Order/CreateOrder.cshtml
@model OrderViewModel

<h2>Create Order</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateOrderPost" method="post">
            <div class="form-group">
                <label asp-for="PizzaStore" class="control-label"></label>
                <input asp-for="PizzaStore" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PaymentMethod" class="control-label"></label>
                @*creates select list with options where value is the value of the members and text is the name of the member of the enum*@
                <select class="form-control" asp-for="PaymentMethod" asp-items="Html.GetEnumSelectList<PaymentMethod>()"></select>
            </div>
            <div class="form-group">
                <label asp-for="Delivered" class="control-label"></label>
                <input type="checkbox" asp-for="Delivered" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                @*creates select list with options where value is Id and text is Fullname from the list of UserDDViewModel*@
                <select asp-for="UserId" asp-items="@(new SelectList(ViewBag.Users, "Id", "FullName"))"></select>
            </div>
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
</div>

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Order/Details.cshtml
@model OrderDetailsViewModel
<h2>Order Details</h2>
<div><a asp-action="AddPizza" asp-controller="Order" asp-route-id="@Model.Id">Add Pizza</a></div>
<ul>
    <li>Price: @Model.Price</li>
    <li>Payment Method: @Model.PaymentMethod</li>
    <li>Pizza Store: @Model.PizzaStore</li>
    <li>User: @Model.UserFullName</li>
    <li>
        <ol>

            @foreach (var pizzaName in Model.PizzaNames)
            {
                <li>@pizzaName <br /> <a asp-action="RemovePizza" asp-controller="Order">Remove Pizza</a></li>
            }
        </ol>
    </li>
</ul>

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Order/Index.cshtml
@model List<OrderDetailsViewModel>


<h2>List of orders:</h2>
<div>
    <a asp-controller="Order" asp-action="CreateOrder">Create Order</a>
</div>
    @foreach (OrderDetailsViewModel order in @Model)
    {
        <ul>
        <li>Price: @order.Price</li>
        <li>Payment Method: @order.PaymentMethod</li>
        <li>Pizza Store: @order.PizzaStore</li>
        <li>User: @order.UserFullName</li>
            <li>
                <ol>

                    @foreach (var pizzaName in order.PizzaNames)
                    {
                        <li>@pizzaName</li>
                    }
                </ol>
            </li>
            <li><a asp-controller="Order" asp-action="Details" asp-route-id="@order.Id">See Details</a></li>
        </ul>
        <hr/>

    }

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Pizza/CreatePizza.cshtml
@model PizzaViewModel

<h2>Create Pizza</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePizzaPost" method="post">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>            
            <div class="form-group">
                <label asp-for="IsOnPromotion" class="control-label"></label>
                <input type="checkbox" asp-for="IsOnPromotion" class="form-control" />
            </div>
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
</div>

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Pizza/Details.cshtml
@model PizzaDetailsViewModel
<h2>Pizza Details</h2>
<p>Pizza: @Model.Name</p>

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Pizza/Index.cshtml
@model List<PizzaDetailsViewModel>


<h2>List of pizzas:</h2>
<div>
    <a asp-controller="Pizza" asp-action="CreatePizza">Create Pizza</a>
</div>
@foreach (PizzaDetailsViewModel pizza in @Model)
{
    <p>Name: @pizza.Name</p>
    <a asp-controller="Pizza" asp-action="Details" asp-route-id="@pizza.Id">See Details</a>
    <hr />

}

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Shared/BadRequest.cshtml
<h2>Your request was incomplete!</h2>

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Shared/ExceptionView.cshtml
<h2>An error occured!</h2>

Class7/SEDC.PizzaApp.Refactored/SEDC.PizzaApp.Refactored/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SEDC.PizzaApp.Refactored</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Pizza App</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><img height="50" src="https://image.flaticon.com/icons/svg/1161/1161623.svg" /></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Order" asp-action="Index">See Orders</a></li>
                    <li><a asp-area="" asp-controller="Pizza" asp-action="Index">See Pizzas</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - SEDC.PizzaApp.Refactored</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>